### PR TITLE
ddns-script: removes linefeed which causes 401 err

### LINKED ISSUE #27693: ddns-scripts-ovh: fails to update IP - unauth
### Package Name

ddns-scripts-ovh

### Maintainer

@davidandreoletti 

### OpenWrt Version

SNAPSHOT

### OpenWrt Target/Subtarget

ramips/mt7621

### Steps to Reproduce

Install latest SNAPSHOT openwrt image
Configure ovh dnsupdate
Trigger update => "HTTP/1.1 401 Unauthorized"

I debugged a bit and the issue is caused by the linefeed at the end of the Auth-header. I will provide a quick fix.

### Actual Behaviour

"HTTP/1.1 401 Unauthorized" instead of "done"

### Confirmation Checklist

- [x] The package is maintained in this repository.
- [x] I understand that issues related to [the base OpenWrt repository](https://github.com/openwrt/openwrt/issues) or [LuCI repository](https://github.com/openwrt/luci/issues) will be closed.
- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by devfaz**
the linefeed at the end causes ovh-api to return 401 even if the password is correct.

Fixes #27693

## 📦 Package Details

**Maintainer:** @feckert @davidandreoletti 

**Description:**
fixes #27693 - caused by linefeed.

---

## ✅ Formalities

- [x] I have reviewed the [CONTRIBUTING.md](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by davidandreoletti — COMMENTED** [review]
Quite odd it was not working for you without the -n option as it did for me.

Could it be your password once all (shell) expansions done produced a newline character?

**Comment by devfaz** [comment]
Doesnt look like there is some hidden linefeed. The password itself is copy&paste from pwgen.
```
+ http_basic_encoding x-x.net-wrt2k25 x
+ local 'user=x-x.net-wrt2k25'
+ local 'password=x'
+ echo x-x.net-wrt2k25:x
+ openssl base64
```
If I copy&paste user and password into "--user"-parameter of curl on my workstation it generates a base64 encoded string without the linefeed at the end. So the correct (lets assume curl is right) behaviour is not having a linefeed at the end. Using echo without "-n" adds a linefeed by default, so we should add the "-n"

**Comment by davidandreoletti** [comment]
> echo without "-n" adds a linefeed by default, so we should add the "-n"

I agree with you.

**Comment by feckert** [comment]
Please bump PKG_RELEASE in the Makefile and also update the commit message body. 
```
the linefeed at the end causes ovh-api to return 401 even if the
password is correct.
```

to 

```
The linefeed at the end causes ovh-api to return 401 even if the
password is correct.
```

File: net/ddns-scripts/files/usr/lib/ddns/update_ovh_com.sh [hunk 1]
```diff
@@ -12,7 +12,7 @@
 http_basic_encoding() {
 	local user="$1"
 	local password="$2"
-	echo "${user}:${password}" | openssl base64 
+	echo -n "${user}:${password}" | openssl base64
```
Comment (systemcrash) [inline net/ddns-scripts/files/usr/lib/ddns/update_ovh_com.sh]: recommend:
```sh
printf "${user}:${password}" | openssl base64 -in /dev/stdin
```

File: net/ddns-scripts/files/usr/lib/ddns/update_ovh_com.sh [hunk 2]
```diff
@@ -12,7 +12,7 @@
 http_basic_encoding() {
 	local user="$1"
 	local password="$2"
-	echo "${user}:${password}" | openssl base64 
+	printf "${user}:${password}" | openssl base64
```
Comment (systemcrash) [inline net/ddns-scripts/files/usr/lib/ddns/update_ovh_com.sh]: `printf "${user}:${password}" | openssl base64 -in /dev/stdin`

**Review by systemcrash — APPROVED** [review]

**Comment by feckert** [comment]
Thanks merged!

**Comment by mundschenk-at** [comment]
Have you tested these changes? I still got an error with current `main` on GL-MT6000. What fixed things was modifying the line to read `echo -n "${user}:${password}" | openssl base64 -A` (I could not get it work with  `printf` or `-in stdin`).

The added `-A` suppresses the line-wrap that is apparently part of earlier RFCs but not wanted for basic auth.

**Comment by danielfdickinson** [comment]
As I mention in https://github.com/openwrt/packages/issues/27526#issuecomment-3677592364 with 24.10.5 OVH is working well for me, so I am not sure the reason for, and implementation of this series of changes is accurate.

**Comment by mundschenk-at** [comment]
@feckert Have you seen the follow-up?

**Comment by systemcrash** [comment]
> As I mention in [#27526 (comment)](https://github.com/openwrt/packages/issues/27526#issuecomment-3677592364) with 24.10.5 OVH is working well for me, so I am not sure the reason for, and implementation of this series of changes is accurate.

This change hasn't been picked to 24.10 IIUC. Good if you can submit a PR with the correction that 'works'.

**Comment by danielfdickinson** [comment]
@systemcrash It is on my list. Hopefully this weekend...Got sick...hopefully soon.
