### PR TITLE
ddns-scripts: fixed ovh dns record update

### LINKED ISSUE #27526: dns-scripts: https://USER:PASSWORD@dns.eu.ovhapis.com/nic/update?system=dyndns&hostname=$HOSTNAME&myip=$IP fails with curl
### Package Name

dns-scripts

### Maintainer

@feckert

### OpenWrt Version

SNAPSHOT

### OpenWrt Target/Subtarget

rockchip/armv8

### Steps to Reproduce

1. Set this uci config

```
# Set curl
uci set ddns.global.use_curl=1

# Set OVH dyndns service update
uci set ddns.PRIMARY_SERVICE_IPV4_1=service
uci set ddns.PRIMARY_SERVICE_IPV4_1.enabled='1'
uci set ddns.PRIMARY_SERVICE_IPV4_1.service_name='ovh.com'
uci set ddns.PRIMARY_SERVICE_IPV4_1.use_ipv6='0'
uci set ddns.PRIMARY_SERVICE_IPV4_1.lookup_host='my-ovh.domain.com'
uci set ddns.PRIMARY_SERVICE_IPV4_1.domain='DOMAIN'
uci set ddns.PRIMARY_SERVICE_IPV4_1.username='USER'
uci set ddns.PRIMARY_SERVICE_IPV4_1.password='PASSWORD'
uci set ddns.PRIMARY_SERVICE_IPV4_1.ip_source='network'
uci set ddns.PRIMARY_SERVICE_IPV4_1.ip_network='wan'
uci set ddns.PRIMARY_SERVICE_IPV4_1.interface='wan'
uci set ddns.PRIMARY_SERVICE_IPV4_1.use_https='1'
uci set ddns.PRIMARY_SERVICE_IPV4_1.cacert='/etc/ssl/certs'
uci set ddns.PRIMARY_SERVICE_IPV4_1.check_unit='minutes'
uci set ddns.PRIMARY_SERVICE_IPV4_1.force_unit='minutes'
uci set ddns.PRIMARY_SERVICE_IPV4_1.retry_unit='seconds'
```

2. commit and reload

```
uci commit ddns
service ddns stop;
service ddns start;
```

3. The ddns script debug logs shows the DNS update failed due to unauthorized user (while the curl exit code is 0) 

```
eval /usr/bin/curl -RsS -o /var/run/ddns/PRIMARY_SERVICE_IPV4_1.dat --stderr /var/run/ddns/PRIMARY_SERVICE_IPV4_1.err --interface pppoe-wan --capath /etc/ssl/certs --noproxy ''"'"'*'"'" ''"'"'https://USER:PASSWORD@dns.eu.ovhapis.com/nic/update?system=dyndns&hostname=DOMAIN&myip=IP'"'"
+ /usr/bin/curl -RsS -o /var/run/ddns/PRIMARY_SERVICE_IPV4_1.dat --stderr /var/run/ddns/PRIMARY_SERVICE_IPV4_1.err --interface pppoe-wan --capath /etc/ssl/certs --noproxy ''"'"'*'"'" ''"'"'https://USER:PASSWORD@dns.eu.ovhapis.com/nic/update?system=dyndns&hostname=DOMAIN&myip=IP'
+ __ERR=0
+ '[' 0 -eq 0 ]
+ return 0
+ cat /var/run/ddns/PRIMARY_SERVICE_IPV4_0.dat
+ write_log 7 'DDNS Provider answered:
{"class":"Client::Unauthorized","message":"Unauthorized"}'
```

**Curl:**
curl 8.15.0 (aarch64-openwrt-linux-gnu) libcurl/8.15.0 mbedTLS/3.6.4 nghttp2/1.66.0
Release-Date: 2025-07-16
Protocols: file ftp ftps http https mqtt
Features: alt-svc HSTS HTTP2 HTTPS-proxy IPv6 Largefile SSL threadsafe UnixSockets

### Actual Behaviour

The authentication to the server has [changed](https://help.ovhcloud.com/csm/en-ie-dns-dynhost?id=kb_article_view&sysparm_article=KB0051641). Here are the changes:
- USER@PASSWORD is not supported anymore and HTTP Basic Authorization must be used. While the doc did not state how to do the authentication, I confirmed the HTTP Basic authentication header allows one to submit an IP update.

### Fix guidance

EDIT: I went the custom script route as curl -u 'xxx:bbb' --basic never sent an HTTP Basic header with the default curl client.

The fix will require to create a custom script for ovh.com. Alternatively add HTTP Basic authentication to the `do_transfer` function, the following needs should be enough:
 - Add wget support for HTTP Basic auth with `wget --user FOO --password BAR`
 - Add curl supports HTTP Basic auth with `curl -u 'FOO:BAR' --basic`
 - ufetch-client: no idea.
 - Add a new option in uci /etc/config/ddns `use_http_basic_auth_authentication` (default: false), to use the "user / password params" as part of HTTP Basic auth for each HTTP client software.

### Confirmation Checklist

- [x] The package is maintained in this repository.
- [x] I understand that issues related to [the base OpenWrt repository](https://github.com/openwrt/openwrt/issues) or [LuCI repository](https://github.com/openwrt/luci/issues) will be closed.
- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by davidandreoletti**
## 📦 Package Details

**Maintainer:** @feckert

**Description:**
Fixes https://github.com/openwrt/packages/issues/27526.

OVH changed its API to update DNS records. It now requires HTTP Basic Authorization header. As such the default ddns-script method to update the DNS record is failing. The fix is to move DNS record updates into its own script/package.

## 🧪 Run Testing Details

- **OpenWrt Version: SNAPSHOTS **
- **OpenWrt Target/Subtarget: rockchip/armv8**
- **OpenWrt Device: NanoPi R4s 4G **

---

## ✅ Formalities

- [X] I have reviewed the [CONTRIBUTING.md](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### If your PR contains a patch:

No patch.

### CODE REVIEW

**Comment by BKPepe** [comment]
@kolacinskikarol In the past, you were doing some changes for OVH ddns-script. Would you mind to take a look at it, please?

**Comment by davidandreoletti** [comment]
@kolacinskikarol @BKPepe This is ready for review.

**Comment by feckert** [comment]
Please bump PKG_RELEASE in the make file. The other things LGTM.
Thanks

**Comment by davidandreoletti** [comment]
> Please bump PKG_RELEASE in the make file. The other things LGTM. Thanks

done.

File: net/ddns-scripts/files/usr/lib/ddns/update_ovh_com.sh [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+# Options passed from /etc/config/ddns:
+# Domain - the domain name managed by OVH (e.g. example.com)
+# Username - the dynhost username of the domain (e.g. myrouter)
+# Password -  the dynhost password of the domain
+
+. /usr/share/libubox/jshn.sh
+
+# base64 encoding
+http_basic_encoding() {
+    local user="$1"
```
Comment (feckert) [inline net/ddns-scripts/files/usr/lib/ddns/update_ovh_com.sh]: Here you use spaces and down in the same file you use tabs.
Please use tabs consistently throughout the file.

Comment (davidandreoletti) [reply net/ddns-scripts/files/usr/lib/ddns/update_ovh_com.sh]: @feckert Good catch. It is fixed now throughout the file. Thank you.

**Comment by feckert** [comment]
Thanks merged!

**Comment by danielfdickinson** [comment]
> It now requires HTTP Basic Authorization header

@davidandreoletti As 24.10.4 and 24.10.5 continue to work for me for the OVH provider, and there are reports that ddns-scripts is failing with curl 8.15.x (https://forum.openwrt.org/t/ddns-fail-to-update-with-curl-installed/244254/11) (which is master but not 24.10.x), I believe the 'root cause' is not a change in the OVH API. The link you provided does not give any indication of an API change that I read.

**Comment by davidandreoletti** [comment]
@danielfdickinson 

I agree with the resolution ([revert once curl's http auth compilation option is re-enabled](https://github.com/openwrt/packages/pull/28174)).

When I encountered the issue (no dns update), I waited a few days thinking someone else would also encounter the bug and post a fix online. Nothing caught my attention. I thought very few people use it.

So I investigated, and found the `http://username:password` can be worked around with HTTP `Authorization: Basic`.

Until today, I was not aware curl had `http auth` disabled, which triggered the issue.

The bug report is unfortunately misleading here (my bad): `The authentication to the server has [changed](https://help.ovhcloud.com/csm/en-ie-dns-dynhost?id=kb_article_view&sysparm_article=KB0051641). Here are the changes:`.

I meant to write `The authentication to the server has changed [compared to the doc](https://help.ovhcloud.com/csm/en-ie-dns-dynhost?id=kb_article_view&sysparm_article=KB0051641). Here are the changes:`.

I am sorry for the confusion and thank you for resolving this. +1

Note: The advantage of the current PR is to be impervious to curl's http auth build option state as it rely on plain HTTP and headers only but I understand consistency is important here too.

**Comment by danielfdickinson** [comment]
@davidandreoletti Thank you for clarifying that. I think not too many people have been using the SNAPSHOTs until 25.12-rc1, who also use OVH provider. With stable (24.10.x) not impacted, there wasn't really anyone to notice. I recently started poking away at the packages repo, and noticed this series of issues and PRs because I use OVH DynHost.
